// Hotel listings
export const GET_HOTEL_LISTING_IN_PROGRESS = 'GET_HOTEL_LISTING_IN_PROGRESS';
export const SET_HOTEL_LISTING = 'SET_HOTEL_LISTING';
export const SET_HOTEL_LISTING_FAILED = 'SET_HOTEL_LISTING_FAILED';
export const GET_HOTEL_LISTING_SUCCESS = 'GET_HOTEL_LISTING_SUCCESS';
